export const browserCoreExamples = [
  "uagent browser status",
  "uagent browser start",
  "uagent browser stop",
  "uagent browser tabs",
  "uagent browser open https://example.com",
  "uagent browser focus abcd1234",
  "uagent browser close abcd1234",
  "uagent browser screenshot",
  "uagent browser screenshot --full-page",
  "uagent browser screenshot --ref 12",
  "uagent browser snapshot",
  "uagent browser snapshot --format aria --limit 200",
  "uagent browser snapshot --efficient",
  "uagent browser snapshot --labels",
];

export const browserActionExamples = [
  "uagent browser navigate https://example.com",
  "uagent browser resize 1280 720",
  "uagent browser click 12 --double",
  'uagent browser type 23 "hello" --submit',
  "uagent browser press Enter",
  "uagent browser hover 44",
  "uagent browser drag 10 11",
  "uagent browser select 9 OptionA OptionB",
  "uagent browser upload /tmp/uagent/uploads/file.pdf",
  'uagent browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "uagent browser dialog --accept",
  'uagent browser wait --text "Done"',
  "uagent browser evaluate --fn '(el) => el.textContent' --ref 7",
  "uagent browser console --level error",
  "uagent browser pdf",
];
